### ISSUE TITLE
ECDC updated excel table population variable

### ISSUE THREAD

**Issue by econ-erik** [mountainMath/CanCovidData#1]
It seems like ECDC has changed column 10 of their table to use 2019 population. The column name is now "popData2019". I believe it involves a simple fix to line 30 of international_import.R. Suggested code below:

`    
select(Country=Country,shortCountry=geoId,countryCode=countryterritoryCode,`Population 2019`=popData2019,
           Date,Confirmed,Deaths=CumulativeDeaths,Cases=cases)
`

I couldn't find `Population 2018` used anywhere else in the helper functions requiring additional updating.

**Comment by econ-erik** [comment]
I tested custom versions of the get_ecdc_data() and get_country_timeline_ecdc_jhs_data() and both worked as expected.

**Comment by mountainMath** [comment]
Thanks for flagging this and providing a solution, looking into it right now.

**Comment by mountainMath** [comment]
Ok, new version is live.

**Comment by econ-erik** [comment]
Thanks for the amazingly quick update and all the public goods in general @mountainMath  :)
